### ISSUE TITLE
one error：

### ISSUE THREAD

**Issue by yun189** [invictus717/MiCo#5]
python inference_demo.py，
error happened：
Traceback (most recent call last):
  File "/mnt/sdb/MiCo/inference_demo.py", line 171, in <module>
    outputs = model.multimodal_encoder.generate(input_ids=init_input_ids,
  File "/home/liran/miniforge3/envs/MiCo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/liran/miniforge3/envs/MiCo/lib/python3.10/site-packages/transformers/generation/utils.py", line 1953, in generate
    result = self._beam_search(
  File "/home/liran/miniforge3/envs/MiCo/lib/python3.10/site-packages/transformers/generation/utils.py", line 3011, in _beam_search
    model_kwargs["past_key_values"] = self._temporary_reorder_cache(
  File "/home/liran/miniforge3/envs/MiCo/lib/python3.10/site-packages/transformers/generation/utils.py", line 2756, in _temporary_reorder_cache
    past_key_values = self._reorder_cache(past_key_values, beam_idx)
  File "/home/liran/miniforge3/envs/MiCo/lib/python3.10/site-packages/transformers/generation/utils.py", line 699, in _reorder_cache
    raise NotImplementedError(
NotImplementedError: Make sure that a `_reorder_cache` function is correctly implemented in model.bert to enable beam search for <class 'model.bert.BertForMaskedLM'>
what can I do for it？

**Comment by invictus717** [comment]
I have never encountered this error before. Maybe it's due to python 3.10...

**Comment by yun189** [comment]
请问您使用python3.10吗？还是其他版本？

**Comment by invictus717** [comment]
我用3.9

**Comment by invictus717** [comment]
我本地debug的时候3.8也用过 你直接改成3.8吧

**Comment by yun189** [comment]
好的，感谢您的回复。

**Comment by yun189** [comment]
非常感谢您的快速解答！用python3.8装了一遍您刚才提供的sh，还是报错：
  File "inference_demo.py", line 2, in <module>
    import torch 
  File "/home/liran/miniforge3/envs/MiCo/lib/python3.8/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory
网上说torch降到2.0.0可以解决问题，请问这个是依赖的版本还是什么原因？

**Comment by invictus717** [comment]
对 这都是一些版本问题 cuda+torch+cudnn+python之间的版本兼容问题 还有一些还会涉及到你的nvidia驱动版本 比较常见
